### ISSUE TITLE
how to use any name for variables?

### ISSUE THREAD

**Issue by sibelius** [asciimath/asciimathml#100]
https://github.com/tylerlong/asciimath-to-latex/issues/5

I'd like to have a formula like this:

```jsx
2*(ind) + 3*(comum)
````
but the result is this:

```jsx
2⋅(∈d)+3⋅(coμm)
```

is there a syntax to avoid parsing `ind` and `comum` ?

**Comment by davidfarmer** [comment]
You can put the words in quotes to treat them as a unit of text:

2*("ind") + 3*("comum")

**Comment by sibelius** [comment]
tks
