### ISSUE TITLE
A home for language development?

### ISSUE THREAD

**Issue by GarkGarcia** [asciimath/asciimathml#110]
Is there a public repository concerning the development of the _asciimath_ language? Is there a place where user can discuss possible changes to the language itself (not `asciimathml`)?

I believe this issues should be considered.

**Comment by GarkGarcia** [comment]
This repository is not the right place to raise this issue, but that's my point 😁️ (there should be a proper place for it)

**Comment by drlippman** [comment]
While this repository houses the AsciiMathML script, it also serves as the reference implementation for the AsciiMath language.  So yes, this repository is the right place to discuss ideas for the language itself.  There is nowhere else.

**Comment by davidfarmer** [comment]
I am also interested in such discussions.

It is sort-of possible to use GItHub issues like the thread of a
newsgroup discussion.  So maybe we can try it until doesn't serve
the need?

**Comment by GarkGarcia** [comment]
Alright, thanks!
