### ISSUE TITLE
mlt, mgt symbols don't work

### ISSUE THREAD

**Issue by fdeitylink** [asciimath/asciimathml#115]
#99 doesn't seem to have worked.
Typing `mlt`/`mgt` yields `m <` and `m >` instead of `<<` and `>>`. The `lt`/`gt` is getting parsed first I suppose. The TeX alts `ll`/`gg` don't work either (produces the characters themselves).

Tested on the [asciimath website](http://asciimath.org)

**Comment by drlippman** [comment]
The AsciiMath website uses MathJax to render the math.  MathJax's version of asciimath tends to lag behind the version in this repo by a few months or more.   MathJax's version hasn't yet incorporated the `mgt` addition.
