### ISSUE TITLE
Add `tilde` combining character to documentation

### ISSUE THREAD

**Issue by manuel489** [asciimath/asciimathml#119]
I've noticed that `tilde` combining character is not listed in [AsciiMath documentation](http://asciimath.org/):

`tilde x` ->  ![capture2](https://user-images.githubusercontent.com/33627611/101970496-28ad1e00-3c01-11eb-8843-91a5f29575e4.PNG)

I think it would be helpful to do so 👍.

Thanks!

**Comment by archiepaulson** [comment]
`mathcal` should be there too. I accidentally discovered that my latex `\mathcal{E}` works in asciimath, which is often used for emf (aka source voltage) in circuits.

**Comment by drlippman** [comment]
`mathcal` is a longhand equivalent to the `cc` font command which is already documented.  But perhaps it would make sense to add a TeX alt column for the font commands.

Any suggestions for improving the asciimath.org documentation would be better added as an issue on https://github.com/asciimath/asciimath.github.io

**Comment by drlippman** [comment]
Got these added
