### ISSUE TITLE
i-hat and j-hat symbols?

### ISSUE THREAD

**Issue by archiepaulson** [asciimath/asciimathml#121]
I'm loving asciimath!  The only thing I'm missing from latex is the Cartesian unit vector j-hat, like this 

2 \hat{\imath} + 2 \hat{\jmath} + 2 \hat{k}

The ascimath `hat j` is not so nice looking. (The i-hat can by done using `hat iota`).

Does a symbol like "jmath" exist?

**Comment by drlippman** [comment]
No, sorry.
