### ISSUE TITLE
Test environment 'collapses' multiple kinds of whitespace into one

### ISSUE THREAD

**Issue by kozross** [asciimath/asciimathml#125]
The [test environment](http://asciimath.org/) responds to any kind of whitespace being entered (and indeed, any _amount_ of consecutive whitespace) by converting it to a single space. This is confusing, not least of all because it doesn't demonstrate how AsciiMath responds to multiple consecutive spaces, for example. Is this intentional, and if so, why?

**Comment by drlippman** [comment]
AsciiMath treats multiple consecutive spaces as if there's only one, so it sounds like it's behaving exactly right.  In AsciiMath, spaces only serve to separate tokens, nothing else.
