### ISSUE TITLE
Vec() crashes updater

### ISSUE THREAD

**Issue by dlevear** [asciimath/asciimathml#130]
Go to asciimath.org. Type "vec()". You will get a Math Processing Error. 
![image](https://user-images.githubusercontent.com/52705716/125316371-12398300-e306-11eb-818c-3720701ccdbf.png)

This message will persist even when you replace "vec()" with something valid.

![image](https://user-images.githubusercontent.com/52705716/125316471-241b2600-e306-11eb-91c6-38413516859f.png)

When I try to replace "vec()" by something, I get errors in the console (Chrome). 

![image](https://user-images.githubusercontent.com/52705716/125316282-f9c96880-e305-11eb-8a5b-b50ad48fe217.png)

This issue seems to be exclusive to the "vec" operation. Typing "hat()" will not cause any issue, and neither will "tilde()" or "bar()" or "dot()" etc.

**Comment by drlippman** [comment]
I see the likely cause in ASCIIMathML.js.  I can fix it here, but it will take a while (often months) for changes here to make their way upstream to MathJax.
