### ISSUE TITLE
support for mathjax 3

### ISSUE THREAD

**Issue by jimy-byerley** [asciimath/asciimathml#137]
Hello and thank you for your efforts in creating asciimath which is much simpler and inutitive than any math syntax before !

I'm currently trying to use in my sphinx documentation. And I'm facing configuration and versions issues.
- It seems asciimath only works with mathjax 2
- sphinx cannot work with any mathjax versions (I don't exactly know the compatible ones) and their support of math expressions doesn't extend to markdown files, so I cannot use their mathjax support.
- I'm using [Myst_parser](https://myst-parser.readthedocs.io/en/latest/index.html) sphinx extension  to transform my markdown with maths, but it only works with mathjax 3

*Myst_parser* allows to change the mathjax config, but it seems that with mathjax 3 no config allows to use asciimath.

Is there plans to feature asciimath for mathjax 3 ? Or am I completely wrong and there is an easy way that is said nowhere ?

**Comment by drlippman** [comment]
MathJax 3 already includes Asciimath as an input format, but the setup isn't quite as simple. See http://docs.mathjax.org/en/latest/input/asciimath.html for how to configure MathJax 3 for Asciimath.  If you have further questions
