### ISSUE TITLE
Please add `∼` (tilde operator) and `≁` (not tilde)

### ISSUE THREAD

**Issue by Epyxoid** [asciimath/asciimathml#140]
They used to express similarity and dissimilarity of two shapes.
[Similarity (geometry) - Wikipedia](https://en.wikipedia.org/wiki/Similarity_(geometry))
[Tilde Operator - Unicode Character Table](https://unicode-table.com/en/223C/)
[Not Tilde - Unicode Character Table](https://unicode-table.com/en/2241/)

The normal tilde key on my keyboard looks really small in asciimath.
[Tilde - Unicode Character Table](https://unicode-table.com/en/007E/)

**Comment by drlippman** [comment]
~ is already an asciimath symbol which is converted to the unicode \u223C when generating mathml.  That was added 2 years ago, and it looks like the most recent MathJax 2 and 3 support them, but not the older version still being used on asciimath.org.

As for "not tilde", there have been several requests for similar additional symbols.  Keep in mind that even if they are added here, it will be months or years before MathJax adds them; it might be easier to modify your mathjax config to add the symbols you want.

**Comment by Epyxoid** [comment]
Oh, I see. So it's already included. Thank you for your help!
