### ISSUE TITLE
Move repository to asciimath organization

### ISSUE THREAD

**Issue by adius** [asciimath/asciimathml#29]
This came already up before, but we didn't really make a decision…
I think we should move it to focus all repositories in one place!

**Comment by adius** [comment]
I think we should finally tackle this issue =P

**Comment by drlippman** [comment]
It's fine with me, if someone knows how to do it :)

**Comment by pkra** [comment]
I have the necessary rights but I was waiting for confirmation from @drlippman and @jipsen .

**Comment by jipsen** [comment]
It's fine with me. (I hope this is unrelated to the AsciiMath inputjax for MathJax since the inclusion of AsciiMath in MathJax has been very useful :)

**Comment by pkra** [comment]
@jipsen thanks. Yes, it's just an organizational change on GitHub.

**Comment by pkra** [comment]
Done.

**Comment by adius** [comment]
:+1:
