### ISSUE TITLE
spaces

### ISSUE THREAD

**Issue by scaljeri** [asciimath/asciimathml#36]
Maybe this is not an issue, but my misunderstanding of spaces in asciimath. 

Consider the following AsciiMath formulas

    `= 30\ 10`
    `\ 30\ 10`

Now, if I run these through `AMTparseAMtoTeX` I get the following out

    '={30}{10}'
    '={30}{10}'

Is there something wrong with the spaces (I've also tried adding 2 `\`) Or is the space ignored by this converter for some reason?

**Comment by drlippman** [comment]
If you are manually feeding these strings into the function, are you escaping your backslashes in your strings? I'm noticing:
AMTparseAMtoTeX("3\ 5")  outputs "{3}{5}", but
AMTparseAMtoTeX("3\\ 5")  outputs "{3}\ {5}"

**Comment by pkra** [comment]
@drlippman I've taken the liberty to edit your post and escape the code so that the double backslash isn't lost

**Comment by scaljeri** [comment]
Ok, this one is my mistake, double slashes indeed work :) sorry
