### ISSUE TITLE
Use of the tex property in the AMsymbols object (array)

### ISSUE THREAD

**Issue by saf-itpro** [asciimath/asciimathml#38]
In ASCIIMathML.js file some tex property values below are clear to me: For example in the following portion of the AMsymbols, inputs alpha , beta, ...,delta in the ASCIIMathML mode will be same as in the tex mode but the input epsi in the ASCIIMathML mode is epsilon in tex mode. I assumes text:null means the ASCIIMathMl input and the text inputs are the same.

But for the case of "Lim" shown under "standard functions" below, the "Lim" does not work in the text mode. I may be misunderstanding the tex property defined in the AMsymbols. Please help. Thanks..Saf

var AMsymbols = [
//some greek symbols
{input:"alpha",  tag:"mi", output:"\u03B1", tex:null, ttype:CONST},
{input:"beta",   tag:"mi", output:"\u03B2", tex:null, ttype:CONST},
{input:"chi",    tag:"mi", output:"\u03C7", tex:null, ttype:CONST},
{input:"delta",  tag:"mi", output:"\u03B4", tex:null, ttype:CONST},
{input:"Delta",  tag:"mo", output:"\u0394", tex:null, ttype:CONST},
{input:"epsi",   tag:"mi", output:"\u03B5", tex:"epsilon", ttype:CONST},
............
//standard functions
{input:"lim",  tag:"mo", output:"lim", tex:null, ttype:UNDEROVER},
{input:"Lim",  tag:"mo", output:"Lim", tex:null, ttype:UNDEROVER},
{input:"sin",  tag:"mo", output:"sin", tex:null, ttype:UNARY, func:true},
{input:"cos",  tag:"mo", output:"cos", tex:null, ttype:UNARY, func:true},

**Comment by drlippman** [comment]
What are you meaning by "in tex mode"?  There is no separate tex mode, unless I'm misunderstanding you.  

The tex attribute in the symbols is used when latex has a different symbol for the equivalent asciimath input. It enables either symbol to be used.  In the case of Lim, typing Lim or \Lim should do the same thing.

<div>-------- Original message --------</div><div>From: saf-itpro <notifications@github.com> </div><div>Date:07/18/2015  11:36 AM  (GMT-08:00) </div><div>To: asciimath/asciimathml <asciimathml@noreply.github.com> </div><div>Subject: [asciimathml] Use of the tex property in the AMsymbols object (array)
  (#38) </div><div>
</div>In ASCIIMathML.js file some tex property values below are clear to me: For example in the following portion of the AMsymbols, inputs alpha , beta, ...,delta in the ASCIIMathML mode will be same as in the tex mode but the input epsi in the ASCIIMathML mode is epsilon in tex mode. I assumes text:null means the ASCIIMathMl input and the text inputs are the same.

But for the case of "Lim" shown under "standard functions" below, the "Lim" does not work in the text mode. I may be misunderstanding the tex property defined in the AMsymbols. Please help. Thanks..Saf

var AMsymbols = [
//some greek symbols
{input:"alpha", tag:"mi", output:"\u03B1", tex:null, ttype:CONST},
{input:"beta", tag:"mi", output:"\u03B2", tex:null, ttype:CONST},
{input:"chi", tag:"mi", output:"\u03C7", tex:null, ttype:CONST},
{input:"delta", tag:"mi", output:"\u03B4", tex:null, ttype:CONST},
{input:"Delta", tag:"mo", output:"\u0394", tex:null, ttype:CONST},
{input:"epsi", tag:"mi", output:"\u03B5", tex:"epsilon", ttype:CONST},
............
//standard functions
{input:"lim", tag:"mo", output:"lim", tex:null, ttype:UNDEROVER},
{input:"Lim", tag:"mo", output:"Lim", tex:null, ttype:UNDEROVER},
{input:"sin", tag:"mo", output:"sin", tex:null, ttype:UNARY, func:true},
{input:"cos", tag:"mo", output:"cos", tex:null, ttype:UNARY, func:true},

**Comment by saf-itpro** [comment]
David, it's probably an issue of my misunderstanding of tex attribute. I was looking for the LaTeX equivalents of the corresponding ASCIIMath inputs in the symbols array. So if the tex attribute is not null then it is the LaTeX equivalent of the corresponding ASCIIMath input (e.g. epsi vs. epsilon). But if tex is null then  that does not necessarily mean that the LaTeX equivalent of the corresponding ASCIIMath input would be the same; for instance, in {input:"divide",   tag:"mo", output:"-:", tex:null, ttype:DEFINITION} the tex attribute is null but \divide does not work in ams-LaTeX. Correct?

**Comment by drlippman** [comment]
First off, its worth noting that the symbols array was never intended to be used to convert asciimath to latex (which isn't to say you can't, just it wasn't intended that way so may not be robust)

For the division symbol, the symbol you referenced is a definition entry, which means it provides an alternate input for another symbol.  In this case, you'd need to consider as a pair:

{input:"-:", tag:"mo", output:"\u00F7", tex:"div", ttype:CONST},
{input:"divide",   tag:"mo", output:"-:", tex:null, ttype:DEFINITION},

The second entry says divide is equivalent to -:.  The first says -: in asciimath is equivalent to \div in tex.

<div>-------- Original message --------</div><div>From: saf-itpro <notifications@github.com> </div><div>Date:07/19/2015  11:17 AM  (GMT-08:00) </div><div>To: asciimath/asciimathml <asciimathml@noreply.github.com> </div><div>Cc: David Lippman <drlippman@yahoo.com> </div><div>Subject: Re: [asciimathml] Use of the tex property in the AMsymbols object
  (array) (#38) </div><div>
</div>David, it's probably an issue of my misunderstanding of tex attribute. I was looking for the LaTeX equivalents of the corresponding ASCIIMath inputs in the symbols array. So if the tex attribute is not null then it is the LaTeX equivalent of the corresponding ASCIIMath input (e.g. epsi vs. epsilon). But if tex is null then that does not necessarily mean that the LaTeX equivalent of the corresponding ASCIIMath input would be the same; for instance, in {input:"divide", tag:"mo", output:"-:", tex:null, ttype:DEFINITION} the tex attribute is null but \divide does not work in ams-LaTeX. Correct?

**Comment by saf-itpro** [comment]
David, thank you for helping me understand the structure of the symbols array. -Saf
