### ISSUE TITLE
asciimath support for augmented matrix

### ISSUE THREAD

**Issue by brennancheung** [asciimath/asciimathml#42]
There is currently no support for in asciimath for rendering an augmented matrix. This would be useful for showing something like Gauss-Jordan elimination.

**Comment by pkra** [comment]
Thanks for moving this upstream. Is this what you have in mind? https://en.wikipedia.org/wiki/Augmented_matrix

**Comment by brennancheung** [comment]
Exactly.

Not sure what would work best for syntax but maybe using the '|' (pipe) character in that column?

    [ [1,2,3,|,4], [1,1,1,|,1] , [2,2,2,|,2] ]

I don't have any strong opinions for one syntax over another.

This is how they do it with the LaTeX version:
http://stackoverflow.com/questions/5584022/how-do-i-render-an-augmented-matrix-with-mathjax

**Comment by drlippman** [comment]
That notation strikes me as reasonable. I'll have to look into what the MathML generated should look like, but will see if there's an easy way to add this.

<div>-------- Original message --------</div><div>From: Brennan Cheung <notifications@github.com> </div><div>Date:09/08/2015  4:32 PM  (GMT-08:00) </div><div>To: asciimath/asciimathml <asciimathml@noreply.github.com> </div><div>Subject: Re: [asciimathml] asciimath support for augmented matrix (#42) </div><div>
</div>Exactly.

Not sure what would work best for syntax but maybe using the '|' (pipe) character in that column?

[ [1,2,3,|,4], [1,1,1,|,1] , [2,2,2,|,2] ]
I don't have any strong opinions for one syntax over another.

This is how they do it with the LaTeX version:
http://stackoverflow.com/questions/5584022/how-do-i-render-an-augmented-matrix-with-mathjax

**Comment by pkra** [comment]
> I'll have to look into what the MathML generated should look like

Something like

`<mtable columnlines="none none solid">`

**Comment by dpvc** [comment]
I'd recommend

    <mtable columnlines="none none solid none">

so that in case there are more columns (like you might use for inverting a matrix), you don't get solid ones between all the ones after the first two columns.
