### ISSUE TITLE
Possible incorrect usage of \matrix

### ISSUE THREAD

**Issue by scaljeri** [asciimath/asciimathml#43]
I have the following formula

    ((2-2); (0-1,5)) = (0 ; text(-)1,5)

When I convert this to latex I get:

    {\left(\matrix{{2}-{2}\right)};{\left({0}-{1,5}}\right)}={\left({0};\text{-}{1,5}\right)}

Which is incorrect, and should be

    {\left(\matrix{2}-{2}\right)};{\left({0}-{1,5}\right)}={\left({0};\text{-}{1,5}\right)}

![math](https://cloud.githubusercontent.com/assets/1078741/10940508/04cada1c-8307-11e5-9759-a0968f5fb429.png)

Could this be a bug or is there something incorrect in the asciimath ?

**Comment by drlippman** [comment]
Is this being generated by the main ASCIImath script, or one of my ASCIImath to TeX converter scripts?
Looking at your original ASCIImath expression, it looks to be like result shouldn't involve matrices at all.
On Nov 4, 2015 6:17 AM, Lucas Calje <notifications@github.com> wrote:I have the following formula

((2-2); (0-1,5)) = (0 ; text(-)1,5)


When I convert this to latex I get:

{\left(\matrix{{2}-{2}\right)};{\left({0}-{1,5}}\right)}={\left({0};\text{-}{1,5}\right)}


Which is incorrect, and should be

{\left(\matrix{2}-{2}\right)};{\left({0}-{1,5}\right)}={\left({0};\text{-}{1,5}\right)}




Could this be a bug or is there something incorrect in the asccimath ?

**Comment by scaljeri** [comment]
This is from `AMTparseAMtoTeX`

**Comment by drlippman** [comment]
OK, I'm looking at this again.  I'm confused by your "it should be" line.  Why should this ASCIIMath generate a matrix at all?  For that matter, if your goal output is the image you included, why are you using the extra set of parens? Why not just use

(2-2); (0-1, 5) = (0; -1,5)

It appears that the official ASCIIMath parser that MathJax uses renders your original expression of

 ((2-2); (0-1,5)) = (0 ; text(-)1,5)

as
![image](https://cloud.githubusercontent.com/assets/190505/10958907/c8340e40-8327-11e5-9124-9fd7b4047a45.png)

which is how I would expect it to be interpreted.

I'll look again at the AMTparseAMtoTeX function and see why it's parsing the expression differently than the official ASCIIMath parser.

**Comment by scaljeri** [comment]
Thanks for looking into this. You're right, it should add the extra set of `(` ... `)` Thnx for the fix!
