### ISSUE TITLE
Examples for underset and overset

### ISSUE THREAD

**Issue by saf-itpro** [asciimath/asciimathml#44]
1. Can we get some examples of the usage of underset and overset in ASCIIMath on the http://asciimath.org/ page?. 2. Are these new features added into MathJax as well? Thanks..Saf

**Comment by drlippman** [comment]
1. It appears even stackrel (which has been around a long time) isn't demoed on the asciimath.org page, nor are the newish ubrace and obrace.  I think @adius has been doing most of the work on those pages - maybe he'll consider adding some examples?

2. They're in the development branch already, but they haven't gotten merged into the MathJax master yet.

**Comment by pkra** [comment]
@drlippman you could merge my PR :-) I've also just updated it a tiny bit.

**Comment by saf-itpro** [comment]
@drlippman Thank you. I've posted the issue on the link you provided. Thanks..Saf

**Comment by adius** [comment]
Sure thing, just post an issue on the asciimath/asciimath.github.io repo and I'll add it
