### ISSUE TITLE
What is the ASCIIMath equivalent of LaTeX commands overrightarrow, widehat

### ISSUE THREAD

**Issue by saf-itpro** [asciimath/asciimathml#45]
In ASCIIMath, how can I write extensible right arrow [as in LaTeX](http://tex.stackexchange.com/q/114321/22810). rarr does not work. Likewise, is there an ASIIMath equivalent of widehat? Thanks..Saf

**Comment by dpvc** [comment]
Try  `overset rarr {...}` and `overset ~ {...}`

**Comment by saf-itpro** [comment]
`overset (rar)(RT)` does not work in MathJax (via following script tag). It just puts the characters rar on top of RT:
<script type="text/javascript"
  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML-full">
</script>

**Comment by dpvc** [comment]
It should be `rarr` not just `rar`.  It works for me.

**Comment by saf-itpro** [comment]
Thank you for the correction. I should have paid attention to what I may be missing.
