### ISSUE TITLE
Question: is there an api to convert from asciimath to latex?

### ISSUE THREAD

**Issue by rileylark** [asciimath/asciimathml#47]
Ahoy! We love asciimath! Great work, and thank you!

Your API is great for converting from asciimath to a rendered equation, but we already have a latex renderer that we're quite happy with, and we'd like to first convert asciimath to latex and then use our existing renderer to get an image from that latex. Do you expose a way to _just_ do the parsing of asciimath & conversion to latex?

Thanks for your great work and for any additional help you have time for! :D

**Comment by drlippman** [comment]
Yes, in the asciimath-based folder, look for ASCIIMathTeXImg.js.  Set the translateOnLoad config option to false so it doesn't auto-translate.  Then you can use the `AMTparseAMtoTeX` function it exposes to translate AsciiMath strings to latex.  

Or, if you're using an image-based renderer that takes the latex on the query string and want autoconversion of asciimath in your document, just uncomment the `AMTcgiloc` line near the top of the script and put the URL of your image renderer.

I'm assuming you already know that MathJax can handle AsciiMath natively, and provides prettier and more accessible display than image-based renderers.  And there are ways to get Katex to work (see [Murray Bourne's work](http://www.intmath.com/cg5/asciimathml-katex-mathjax.php) for example) if MathJax is too slow for you.

**Comment by pkra** [comment]
Just a thought. It would be nice to integrate that into MathJax as well to provide more copy&paste options.

**Comment by rileylark** [comment]
Awesome, thanks for your help! This is a great project. We make a product for K-12 teachers & students, and asciimath in general is a huge step towards helping them write math into their computers.

**Comment by drlippman** [comment]
Interesting, though I don't think there'd be an easy way to do this.
On Mar 22, 2016 10:09 AM, Peter Krautzberger <notifications@github.com> wrote:Just a thought. It would be nice to integrate that into MathJax as well to provide more copy&paste options.

**Comment by spicyj** [comment]
@drlippman @scaljeri Would you be willing to relicense ASCIIMathTeXImg.js (and the .php) under the MIT license? (Recall that ASCIIMathML.js was already relicensed in 41cee43d903fd89b6b23ac04ef78db7e4b105254.)

**Comment by drlippman** [comment]
I totally forgot that we had relicensed ASCIIMathML under MIT.  Sure, I'm fine with all my derivative works being licensed the same as the original.

**Comment by scaljeri** [comment]
Not sure if I have anything to say here, but I'm fine with MIT!

**Comment by saivan** [comment]
Well `\class` and `\id` are both supported by mathjax, and can be defined in any latex environment.
