### ISSUE TITLE
varepsilon

### ISSUE THREAD

**Issue by aslakr** [asciimath/asciimathml#56]
```js
{input:"varepsilon", tag:"mi", output:"\u025B", tex:null, ttype:CONST},
```
U+025B is ɛ (latin epsilon), not

```xml
<!ENTITY varepsilon       "&#x003F5;" ><!--GREEK LUNATE EPSILON SYMBOL -->
```

as it should be?

**Comment by drlippman** [comment]
It appears that there is [inconsistency](https://www.w3.org/2003/entities/2007doc/#epsilon) between tex and unicode in terms of the epsilons.  

I'm not sure why Peter chose the original mapping he did, but for sake of backwards compatibility, I don't think we can change the definitions now.
