### ISSUE TITLE
Extension request: (:A:| Bra and ket |:B:) vector support with new space-less separator :| and |: and :|: (use << and >> for regular angle bracketing)

### ISSUE THREAD

**Issue by frevds** [asciimath/asciimathml#58]
This looks fine: 
`|A:)(:A|`

This doesn't: 

`|A:)(:A| * 1/2`

because the parser thinks the last (: opens a bracket that is not closed and includes all the rest in the sizing. 

However, you have both (: ... :) and << ... >> (undocumented) for the same angle bracketing: 

```
{input:"(:", tag:"mo", output:"\u2329", tex:"langle", ttype:LEFTBRACKET}, 
{input:":)", tag:"mo", output:"\u232A", tex:"rangle", ttype:RIGHTBRACKET}, 
{input:"<<", tag:"mo", output:"\u2329", tex:null, ttype:LEFTBRACKET}, 
{input:">>", tag:"mo", output:"\u232A", tex:null, ttype:RIGHTBRACKET}, 
```

I suggest you use "(:" and ":)" together with a new ":|", "|:" or ":|:" for bra and ket vectors with no spacing, where a "(:" is closed by ":|", while a "|:" is closed by ":)" and keep "<<" and ">>" for regular bracketing, like so: 

`(:A:|` (bra)
`|:B:)` (ket)
`(:A:|:B:)` (bra-ket)
`(:A:|:B:|:C:)` (sandwich)

This notation is important for quantum physics. 

The pipe | is currently treated as a matrix column separator, making it look very ugly when using it for bras and kets unless one modifies the stylesheet, which then tampers with the whole absolute positioning. The only way currently is to separate all expressions in order to reset the sizing. 

Thanks for listening.

**Comment by frevds** [comment]
Here is a little workaround snippet to use with MathJax in order to introduce the new opening and closing pendents for ket and bra vectors: 

```
<script type="text/javascript">
  window.MathJax = 
  {
    AuthorInit: function()
    {
      MathJax.Hub.Register.StartupHook("End Config", function()
      {
          var symbols = MathJax.InputJax.AsciiMath.AM.symbols; 
          symbols.unshift({input:":|:", tag:"mo", output:"|", tex:null, ttype:0/*CONST*/}); 
          symbols.unshift({input:":|", tag:"mo", output:"|", tex:null, ttype:5/*LEFTBRACKET*/}); 
          symbols.unshift({input:"|:", tag:"mo", output:"|", tex:null, ttype:4/*RIGHTBRACKET*/}); 
      });
    }
  };
</script>
```

The < and | are stretched vertically whenever the content requires it but are otherwise closed brackets. 

 `1/2*(:A:|*1/2`  (bra)
 `1/2*|:B:)*1/2`  (ket)
 `1/2*(:A:|:B:)*1/2`  (bra-ket)
 `1/2*(:A:|:B:|:C:)*1/2`  (sandwich)
 `1/(2/3)*(:1/2*D:|:E:)*4/(5/6)` (stretch)

It's not ideal but better than nothing. 

![preview](https://cloud.githubusercontent.com/assets/5341447/14764281/849a95ca-09b2-11e6-9deb-ced39b17009d.png)

**Comment by drlippman** [comment]
Interesting notion. Certainly is a way to remove the ambiguity with | as a bracket.
