### ISSUE TITLE
underline() is  not working in preview html option

### ISSUE THREAD

**Issue by shahpiyushn** [asciimath/asciimathml#70]
(AB)_16 = (underline{"         "})_8

Asciimath.

underline() is working fine in HTML-CSS and common html option but
it is not working in MathRenderer->preview html option.

So please solve this issue.

**Comment by drlippman** [comment]
Unfortunately, this issue isn't something we can help with, as it's not related to what we work on. This repository only works on the asciimath input syntax and the original raw mathml generator.  The rendering method you're describing is done by MathJax, and you should report this issue to them, in the MathJax/MathJax repository.
