### ISSUE TITLE
Make embedding compatible with markdown rendering

### ISSUE THREAD

**Issue by pakoito** [asciimath/asciimathml#72]
Great job and awesome idea! This rendering style has been sorely missing from README all around github.

Now, the same way we have a somewhat common spec for markdown using \`bla\` for inline code and 
\```
bla
\``` 
for multi line code, it'd be great if MD and this library were fully compatible.

At the moment, triple backtick allows you to specify a language and some renderers will do syntactic highlighting.
\```java
\```

It'd be great if there was a way of specifying  ```asciimath in these blocks too.

**Comment by drlippman** [comment]
You can adjust the configuration to change the delimiter used for AsciiMath so it doesn't conflict.  If you're using MathJax to render AsciiMath, their [documentation](http://docs.mathjax.org/en/latest/asciimath.html) shows how to change the delimiters.
