### ISSUE TITLE
Bug in string literals

### ISSUE THREAD

**Issue by straz** [asciimath/asciimathml#74]
When I use a literal string to indicate capitalization, AsciiMath fails to preserve it. It looks like it finds hard-coded substrings like `cos` and `sin` even when they're clearly not functions, and are inside a string literal.

**Example:**
`"Cost Charged" = .2 * "Days Since Sale"`
 => 
`cost Charged = .2 * Days since Sale`

**Analysis:**
Capitalization of string literals is buggy. **Please don't** un-capitalize reserved words inside string literals.

**Comment by straz** [comment]
**Hackish workaround:**

I'm breaking up the string literals by using a zero-width non-breaking space character. I.e. I write `"C&#xfeff;ost"` instead of `"Cost"`. Yuk, but at least it works. I sure would welcome a cleaner solution, thank you.

**Comment by drlippman** [comment]
Confirmed.  This is due to my admittedly lazy solution to handling capitalized functions like `Sin`.

I'll see if I can come up with a better solution.  Probably we need to create separate symbols for the capitalized functions.
