### ISSUE TITLE
Vector Displays

### ISSUE THREAD

**Issue by saivan** [asciimath/asciimathml#77]
I have a problem where vectors written with asciimath don't display properly, for example compare 

LATEX (with mathjax)

Typeset with

`\vec r = \begin{bmatrix}3 \\ 2 \end{bmatrix}`

![image](https://user-images.githubusercontent.com/8543370/32817123-47f766fa-ca10-11e7-804a-b9f7d67f76d0.png)

ASCIIMATH (with mathjax)

`vec(r) = [[3], [2]]`

![image](https://user-images.githubusercontent.com/8543370/32817130-532631e6-ca10-11e7-8a7d-dc094e7743ec.png)

Is there any way to avoid that huge arrow?

**Comment by drlippman** [comment]
AsciiMath uses the U+2192 [unicode symbol](https://en.wikipedia.org/wiki/Template:Unicode_chart_Arrows) (Rightwards arrow) for vectors, which is the same symbol MathJax uses in their TeX renderer.  It looks like MathJax generates different MathML than AsciiMath does, though: AsciiMath produces an `<mover>` inline with the other text elements, but MathJax's TeX jax puts the `<mover>` inside a `<mrow>`.  This seems like it might be a MathJax issue, not an AsciiMath issue, but maybe @pkra can shed some light on that.

**Comment by drlippman** [comment]
I was wrong, it wasn't the `<mrow>` making the difference, it was a `stretchy="false"` attribute on the `<mo>` tag for the accent.   Unfortunately, that same attribute that makes the arrow nice and small on a single character also makes `\(\vec{ABC}\)` display as 
![image](https://user-images.githubusercontent.com/190505/32821918-d3603842-c98a-11e7-9628-35321539acd8.png), which I'd argue isn't ideal either.

**Comment by pkra** [comment]
> it wasn't the <mrow> making the difference, it was a stretchy="false" attribute on the <mo> tag for the accent. 

That's correct. The asciimath parser would have to check the length of the base to get this right, I suspect.

**Comment by saivan** [comment]
I mean, setting `stretchy="true"` when multiple characters are surrounded by vec and `stretchy="false"` when only one is provided could work right?

**Comment by pkra** [comment]
> I mean, setting stretchy="true" when multiple characters are surrounded by vec and stretchy="false" when only one is provided could work right?

That's correct.

**Comment by drlippman** [comment]
It strikes me as a bit odd that MathJax doesn't "stretch" the arrow to be small when it's a single character, but setting `stretchy="false"` on a single character seems like an easy enough hackaround.  And Firefox's native renderer seems to display them the same on single characters, so changing it won't break behavior there. I'll see what I can do.

**Comment by pkra** [comment]
> It strikes me as a bit odd that MathJax doesn't "stretch" the arrow to be small when it's a single character, 

IIRC it's because MathML and TeX layout disagree on stretchy behavior (but we ensure that TeX input gets TeX-like output).

**Comment by drlippman** [comment]
Should the `stretchy="false"` on single characters be true for all accents?  It looks like I may have to limit it, as some accents, like `ul` and `obrace` don't seem to render right without stretchy [(example)](https://jsfiddle.net/dlippman/1frmash3/) and some accents like `hat` seem to look (arguably) better with stretchy even on single characters.

**Comment by pkra** [comment]
> Should the stretchy="false" on single characters be true for all accents?

It's as stylistic preference; I don't have an opinion.

**Comment by MrSystem** [comment]
The code implemented to fix this issue is broken.
The following inputs produce invalid markup:

![invalid markup](https://user-images.githubusercontent.com/16069471/33521032-92e1194a-d7c6-11e7-9c57-94390e95c5c5.png)

**Comment by drlippman** [comment]
@MrSystem, the code seems to work just fine in FireFox 57.  Please let us know what browser you are experiencing this in, and please use the inspector and screenshot the MathML being generated so we can try to track down the issue, if there is one.

**Comment by MrSystem** [comment]
Yeah, it works. Sorry!

**Comment by saivan** [comment]
Not sure if I missed something here, but on the website http://asciimath.org/, 
it still has the old behaviour, also - mathjax-node still seems to behave like this.

**Comment by drlippman** [comment]
No, MathJax is not automatically updated when AsciiMath updates.  They have a scheduled release cycle, and plan their releases well in advance, so a change to AsciiMath may take a few months to make it into MathJax.  And asciimath.org uses MathJax for rendering, so it is similarly delayed in updates.

**Comment by saivan** [comment]
Oh okay understood :P I really appreciate that :) Then the next question would be, is there any easy way to use asciimath in mathjax node for the time being, or is that something we should wait for the next release for?

**Comment by drlippman** [comment]
I know nothing about mathjax-node, so can't answer for sure.  But I'm guessing you could swap out the existing `jax/input/AsciiMath/jax.js` from your MathJax install for the version I keep in this repo, in `mathjax/jax.js`.  Fair warning: I don't actually test that file when I update it :)
