### ISSUE TITLE
Suggested symbols

### ISSUE THREAD

**Issue by hgiesel** [asciimath/asciimathml#81]
<a href="https://www.codecogs.com/eqnedit.php?latex=\dashv" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dashv" title="\dashv" /></a>
asciimathml already supports <a href="https://www.codecogs.com/eqnedit.php?latex=\vdash" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\vdash" title="\vdash" /></a>, so why not? One usage is showing adjoint functors. Suggested input would `--|`, to mirror `|--`

<a href="https://www.codecogs.com/eqnedit.php?latex=\triangleleft&space;~&space;~&space;\triangleright" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\triangleleft&space;~&space;~&space;\triangleright" title="\triangleleft ~ ~ \triangleright" /></a>
This is used for showing normal subgroups, but there might also other uses. Suggested input would be `<|`, and `|>`.

**Comment by drlippman** [comment]
Thanks for the suggestion.  For the triangle operators, my only concern would be that it might cause backwards compatibility issues, for someone who's written something like `|x|>3` without leaving spaces.

FWIW, if you're using MathJax for display, you could add these symbols yourself using a custom config like:
```
<script type="text/x-mathjax-config">
  MathJax.Hub.Register.StartupHook("AsciiMath Jax Ready",function () {
    AM = MathJax.InputJax.AsciiMath.AM;
    AM.newsymbol({input:"--|", tag:"mo", output:"\u22A3", tex:"dashv", ttype:AM.TOKEN.CONST});
  });
</script>
```

**Comment by hgiesel** [comment]
I consider it a golden rule to always surround operators with spaces, but anyway ;)

And thanks for the suggestion. But because 99% of the time I look at my markup through a text editor anyway, I don't mind too much, but I would to love to see the syntax be expanded to cover more use cases.
