### ISSUE TITLE
Minus plus

### ISSUE THREAD

**Issue by drlippman** [asciimath/asciimathml#93]
Asciimath had the +- symbol, but no -+.  Might be nice to add one.

**Comment by jnowmbro** [comment]
You can fake the -+ by using: frac{}{+}

**Comment by jnowmbro** [comment]
This is a better solution. Code -+ by using: bar +
for example:
asciimath:[(cos(theta +- phi) = cos theta cos phi bar + sin theta sin phi)]
will give you:
![image](https://user-images.githubusercontent.com/48606891/100908797-c32e9400-3480-11eb-9d34-fe1974b81c91.png)
