### ISSUE TITLE
Much less than, much greater than symbols

### ISSUE THREAD

**Issue by TMiguelT** [asciimath/asciimathml#96]
It would be nice to have ≪ and ≫ in asciimath

**Comment by drlippman** [comment]
Unfortunately << and >> are already used as input symbols for angle brakets, so I'm not sure what a reasonable input symbol for these would be.

**Comment by TMiguelT** [comment]
I think a text-based symbol would be fine. `mtg` and `mlt` would be fine

**Comment by davidfarmer** [comment]
In the areas where I do research, the expression

f << g

has the same meaning as

f = O(g) ,
where big-O notation is being used in that equation.

So in that context, ll and gg would be reasonable notations.

However, in that context << does *not* mean "much less than".

See
https://math.stackexchange.com/questions/199753/how-does-one-read-aloud-vinogradovs-notation-ll-and-ll-epsilon

It could be a bad idea to implement notation with a
different meaning that is commonly used.

**Comment by drlippman** [comment]
Thanks David, it's helpful to know the symbol has other meanings in other contexts.

I agree that reusing the LaTeX symbols, ll and gg, seems like a reasonable approach.

**Comment by Javarome** [comment]
Hi, I would need that one too :)
